Course grading page
thenicekat/handoutsforyou pull request #25
Opened 2024-10-19 05:29 UTC by proinators

## Description

<pre>
Introducing a Course grading page, where midsem grades from ERP can be uploaded as images to the website for each course.
</pre>

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New website feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New script (new python script for handouts handling)
- [ ] New resource (new file that is added)
  - [ ] Adding new / updating notes
  - [ ] Adding new / updating handouts
  - [ ] Adding new / updating chronicles
  - [ ] Adding new / updating reviews
- [ ] Misc (explain in description)

## Checklist:

- [x] I used `pnpm` for my project dependencies
- [x] I didnt push any `.env` files

2024-10-19 06:25 UTC, thenicekat commented on pages/courses/grading/index.tsx
> +    let prereqs = fs.readFileSync("./public/prereqs.json").toString();
huh?

2024-10-19 06:25 UTC, thenicekat commented on types/CourseGrading.tsx
New line at EOF

2024-10-20 20:01 UTC, thenicekat requested changes

2024-10-20 20:01 UTC, thenicekat commented on pages/api/courses/grading/get.ts
> +            message: 'Course reviews are only available for BITS Hyderabad students',
```suggestion
            message: 'Midsem grading feature is only available for BITS Hyderabad students',
```

2024-10-22 12:08 UTC, proinators commented on pages/api/courses/grading/get.ts
> +            message: 'Course reviews are only available for BITS Hyderabad students',
Done

2024-10-22 12:11 UTC, thenicekat approved these changes

2024-10-22 12:11 UTC, thenicekat commented on pages/api/courses/grading/add.ts
EOF.

2024-10-22 12:11 UTC, thenicekat commented on pages/courses/grading/add.tsx
Just verify edge cases.

2024-10-22 12:14 UTC, proinators commented on pages/api/courses/grading/add.ts
Done

2024-10-22 16:48 UTC, merged